### ISSUE TITLE
Examples can't run by No static method obtainVisionSkuUserToken?

### ISSUE THREAD

**Issue by h3clikejava** [mapbox/mapbox-vision-android#214]
java.lang.NoSuchMethodError: No static method obtainVisionSkuUserToken(Ljava/lang/String;)Ljava/lang/String; in class Lcom/mapbox/android/accounts/v1/MapboxAccounts; or its super classes (declaration of 'com.mapbox.android.accounts.v1.MapboxAccounts' appears in /data/app/com.mapbox.vision.examples-kEwyjK4ToZH_BBLUiB-mCQ==/base.apk!classes3.dex)
        at com.mapbox.vision.mobile.core.account.AccountManager$Impl.refreshSkuToken(AccountManager.kt:46)
        at com.mapbox.vision.mobile.core.account.AccountManager$Impl.resetAndRescheduleToken(AccountManager.kt:32)
        at com.mapbox.vision.mobile.core.account.AccountManager$Impl.<clinit>(AccountManager.kt:26)
        at com.mapbox.vision.VisionManager.create(VisionManager.kt:217)
        at com.mapbox.vision.VisionManager.create$default(VisionManager.kt:181)
        at com.mapbox.vision.VisionManager.create(Unknown Source:2)
        at com.mapbox.vision.examples.ArActivity.startVisionManager(ArActivity.java:112)
        at com.mapbox.vision.examples.ArActivity.onPermissionsGranted(ArActivity.java:91)
        at com.mapbox.vision.examples.BaseActivity.onCreate(BaseActivity.java:52)
        at android.app.Activity.performCreate(Activity.java:7285)
        at android.app.Activity.performCreate(Activity.java:7276)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3152)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3320)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)

**Comment by yunikkk** [comment]
We'll fix the dependency issues, the method was added in the 0.3.0 version of account lib, while some other mapbox dependencies use 0.2.0.
Meanwhile you can fix that on your side by forcing version manually
```
    implementation("com.mapbox.mapboxsdk:mapbox-android-accounts:0.3.0") {
        force = true
    }
```
