### ISSUE TITLE
 No virtual method setBaseUrl(Ljava/lang/String;)V in class Lcom/mapbox/android/telemetry/MapboxTelemetry; or its super classes

### ISSUE THREAD

**Issue by karthika-89** [mapbox/mapbox-vision-android#216]
I am using a ### **ONEPLUS3T** device.
I am getting the following error log when I tried to get location updates from a mocker app.

java.lang.NoSuchMethodError: No virtual method setBaseUrl(Ljava/lang/String;)V in class Lcom/mapbox/android/telemetry/MapboxTelemetry; or its super classes (declaration of 'com.mapbox.android.telemetry.MapboxTelemetry' appears in /data/app/com.kml.rigapplication-qV8T-1W7fOnP7CNy8oc6ew==/base.apk!classes4.dex)
        at com.mapbox.vision.sync.SessionManager$Impl.configMapboxTelemetry(SessionManager.kt:191)
        at com.mapbox.vision.sync.SessionManager$Impl.setCountry(SessionManager.kt:100)
        at com.mapbox.vision.VisionManager$start$1$1.run(VisionManager.kt:255)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by kiryldz** [comment]
Hi @karthika-89 !
Please try adding this code to app level `build.gradle`

`
api ("com.mapbox.mapboxsdk:mapbox-android-telemetry:4.7.0") {
        force = true
    }
`

**Comment by kiryldz** [comment]
Closing due to inactivity.
