### ISSUE TITLE
crash at launch java.lang.NoSuchMethodError: No static method obtainVisionSkuUserToken

### ISSUE THREAD

**Issue by DmitriyYakovlev** [mapbox/mapbox-vision-android#227]
E/AndroidRuntime: FATAL EXCEPTION: main
	Process: com.mapbox.vision.examples, PID: 6772
	java.lang.NoSuchMethodError: No static method obtainVisionSkuUserToken(Ljava/lang/String;)Ljava/lang/String; in class Lcom/mapbox/android/accounts/v1/MapboxAccounts; or its super classes (declaration of 'com.mapbox.android.accounts.v1.MapboxAccounts' appears in /data/app/com.mapbox.vision.examples-mO9gRjyu-FrWuYJ0CLMVFg==/base.apk)
		at com.mapbox.vision.mobile.core.account.AccountManager$Impl.refreshSkuToken(AccountManager.kt:46)
		at com.mapbox.vision.mobile.core.account.AccountManager$Impl.resetAndRescheduleToken(AccountManager.kt:32)
		at com.mapbox.vision.mobile.core.account.AccountManager$Impl.<clinit>(AccountManager.kt:26)
		at com.mapbox.vision.VisionManager.create(VisionManager.kt:210)
		at com.mapbox.vision.VisionManager.create$default(VisionManager.kt:182)
		at com.mapbox.vision.examples.ArActivityKt.startVisionManager(ArActivityKt.kt:107)
		at com.mapbox.vision.examples.ArActivityKt.onPermissionsGranted(ArActivityKt.kt:84)
		at com.mapbox.vision.examples.BaseActivity.onRequestPermissionsResult(BaseActivity.java:101)
		at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8409)
		at android.app.Activity.dispatchActivityResult(Activity.java:8254)
		at android.app.ActivityThread.deliverResults(ActivityThread.java:4898)
		at android.app.ActivityThread.handleSendResult(ActivityThread.java:4946)
		at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
		at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
		at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
		at android.os.Handler.dispatchMessage(Handler.java:107)
		at android.os.Looper.loop(Looper.java:224)
		at android.app.ActivityThread.main(ActivityThread.java:7520)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/MQSEventManagerDelegate: failed to get MQSService.

**Comment by yunikkk** [comment]
Do you get this error building Teaser app? 

You should be using new version of accounts lib, `com.mapbox.mapboxsdk:mapbox-android-accounts:0.3.0` of newer. Other mapbox dependencies may depend on older accounts lib, thus Vision crashes referencing missing functions

**Comment by DmitriyYakovlev** [comment]
Hi @yunikkk, 
this is not from Teaser, this is from the current repo.
There was an issue with resolving of dependencies, like 
ERROR: Failed to resolve: com.mapbox.vision:mapbox-android-vision:0.11.0
But, I have applied .aar files, downloaded from Mapbox's site. they has the same 0.11.0

**Comment by yunikkk** [comment]
@DmitriyYakovlev ah, if you are using direct `aar` files then you'll need to apply two more mapbox libs :
`com.mapbox.mapboxsdk:mapbox-android-accounts:0.3.0` and `com.mapbox.mapboxsdk:mapbox-android-telemetry:4.7.3`.

Could you please also describe why did you have the issue with resolving maven dependency? Did you added your token as shown in https://vision.mapbox.com/install/ ? Does the token have `vision:download` scope?

**Comment by RaajputSingh** [comment]
@yunikkk thanks for the solution.

**Comment by yunikkk** [comment]
Juts added instructions about the necessary dependencies to the [install docs](https://vision.mapbox.com/install/), closing the issue
