### ISSUE TITLE
Demo running issues

### ISSUE THREAD

**Issue by CloudWangASP** [mapbox/mapbox-vision-android#248]
Hi, I try to run this demo on my Samsung S9 phone with external video source,however it didn't recognize traffic signs and road，so how should I use this project to see the AR effect？

Here are my steps:

1. Compile project and install to my phone(Then I got seven apk on my phone)
2. Download driving video from internet, and replace the "PATH_TO_VIDEO_FILE" const in "ExternalVideoSourceActivityKt" with this video absolute path.
3. I also try to change “ROUTE_ORIGIN” & “ROUTE_DESTINATION” in “ArActivityKt” with real lat & lon.

Is there anything wrong or missing in the above steps?

**Comment by kiryldz** [comment]
Hi @CloudWangASP ,

1. You actually have one APK, but 7 __independent__ launcher activities.
2. `ExternalVideoSourceActivityKt` just shows an example of playing __any__ video file (by default camera is used), there is actually no AR or any other logic in this activity.
3. Setting route origin and route destination should be actually enough but in order for AR to work you should calibrate the device.
More about calibration:
https://docs.mapbox.com/android/vision/overview/vision-basics/#what-are-the-requirements-for-camera-calibration
More about ways of testing and development:
https://docs.mapbox.com/android/vision/overview/testing-and-development/

**Comment by CloudWangASP** [comment]
Lately I try to run the project with Ar or ArCustomizationActivity, when run to this code [VisionManager.create()].I got error log below:

2020-05-26 12:08:46.869 18631-18631/com.mapbox.vision.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.vision.examples, PID: 18631
    java.lang.Error: std::exception
        at com.mapbox.vision.mobile.core.NativeVisionManager.initialize(Native Method)
        at com.mapbox.vision.mobile.core.NativeVisionManager.<init>(NativeVisionManager.kt:40)
        at com.mapbox.vision.VisionManager.create(VisionManager.kt:209)
        at com.mapbox.vision.VisionManager.create$default(VisionManager.kt:188)
        at com.mapbox.vision.examples.ArActivityKt.startVisionManager(ArActivityKt.kt:127)
        at com.mapbox.vision.examples.ArActivityKt.access$startVisionManager(ArActivityKt.kt:44)
        at com.mapbox.vision.examples.ArActivityKt$initViews$1.onClick(ArActivityKt.kt:107)
        at android.view.View.performClick(View.java:6877)
        at android.widget.TextView.performClick(TextView.java:12651)
        at android.view.View$PerformClick.run(View.java:26069)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

BTW：Do you have ready-made AR effect demonstration video link to show the capabilities of this SDK？Thanks！

**Comment by yunikkk** [comment]
@CloudWangASP to confirm - have you customized example somehow? Do you build it from the master branch?

Regarding the visuals for the SDK capabilities: there are some gifs at the toturials help section here https://docs.mapbox.com/help/tutorials/#vision
