### ISSUE TITLE
Unable to run demo

### ISSUE THREAD

**Issue by R00iBaard** [mapbox/mapbox-vision-android#252]
Hi there, Im trying to get the demo running on my Quectel SC66 dev kit but get the following error when the application launches.
Any idea what the problem is?

> 06/26 09:56:54: Launching 'Examples' on Synap AIM-G1.
> $ adb shell am start -n "com.mapbox.vision.examples/com.mapbox.vision.examples.CustomDetectionActivityKt" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
> Connected to process 13243 on device 'synap-aim_g1-d'.
> Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
> I/Zygote: seccomp disabled by setenforce 0
> I/vision.example: Late-enabling -Xcheck:jni
> I/Perf: Connecting to perf service.
> I/vision.example: Thread[1,tid=13243,Native,Thread*=0x753fa14c00,peer=0x73e2aac8,"main"] recursive attempt to load library "/data/app/com.mapbox.vision.examples-hzQclmX6SExPmc9cRyahVA==/base.apk!/lib/arm64-v8a/libvision-sdk-wrapper.so"
> I/com.mapbox.vision.examples: type=1400 audit(0.0:1729): avc: denied { search } for comm=45474C20496E6974 name="gpu" dev="mmcblk0p67" ino=783427 scontext=u:r:untrusted_app:s0:c100,c256,c512,c768 tcontext=u:object_r:vendor_gles_data_file:s0 tclass=dir permissive=1
> W/vision.example: Accessing hidden method Landroid/graphics/drawable/Drawable;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, linking)
> W/vision.example: Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)
>     Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)
>     Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
>     Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
> W/vision.example: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
> W/vision.example: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
> W/vision.example: Accessing hidden method Landroid/widget/TextView;->getTextDirectionHeuristic()Landroid/text/TextDirectionHeuristic; (light greylist, linking)
> I/CameraManagerGlobal: Connecting to camera service
> I/vision.examples: type=1400 audit(0.0:1730): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=13452 scontext=u:r:untrusted_app:s0:c100,c256,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=1
> W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 2
>     [soar.cts] ignore the status update of camera: 3
> D/StagefrightPluginLoader: Failed to load library: libstagefright_ccodec.so (dlopen failed: library "libstagefright_ccodec.so" not found)
>     Handle or CreateInputSurface symbol is null
> I/OMXClient: IOmx service obtained
> D/OpenGLRenderer: Skia GL Pipeline
> D/NetworkSecurityConfig: No Network Security Config specified, using platform default
> W/vision.example: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (light greylist, reflection)
>     Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setHostname(Ljava/lang/String;)V (light greylist, reflection)
>     Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (light greylist, reflection)
>     Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (light greylist, reflection)
>     Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
>     Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
>     Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
> W/vision.example: Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (light greylist, reflection)
> I/Vision-Camera2: attach videoSourceListener, hash=253213819
> D/RenderScript HIDL Adaptation: IRenderScriptDevice::getService()
> D/RenderScript HIDL Adaptation: IRenderScriptDevice::getService() returned 0x7537191520
>     HIDL successfully loaded.
> V/RenderScript: Successfully loaded runtime: libRSDriver_adreno.so
> D/: Successfully queried cache dir: /data/user_de/0/com.mapbox.vision.examples/code_cache
> D/RenderScript: Setting cache dir: /data/user_de/0/com.mapbox.vision.examples/code_cache
> I/Vision-Camera2: CameraDevice onOpened
> I/Vision-Camera2: createCaptureSession from CameraDevice onOpened()
>     createCaptureSession with 1 surfaces
> I/Vision-Camera2: CameraCaptureSession onConfigured hash=84928591
> I/Vision-Camera2: CameraCaptureSession onReady hash=84928591
> I/vision.examples: type=1400 audit(0.0:1733): avc: denied { getattr } for path="/system/xbin/su" dev="dm-0" ino=38 scontext=u:r:untrusted_app:s0:c100,c256,c512,c768 tcontext=u:object_r:su_exec:s0 tclass=file permissive=1
> A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x24 in tid 13243 (vision.examples), pid 13243 (vision.examples)
> W/vision.example: Accessing hidden field Ljava/lang/Enum;->ordinal:I (light greylist, JNI)

**Comment by kiryldz** [comment]
Hi @R00iBaard !
Several questions here:
1) Please attach full log, your log does not contain an actual error - it's described below `A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x24 in tid 13243 (vision.examples), pid 13243 (vision.examples)`
2) Could you please confirm that your device is not rooted.

**Comment by R00iBaard** [comment]
> Hi @R00iBaard !
> Several questions here:
> 
> 1. Please attach full log, your log does not contain an actual error - it's described below `A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x24 in tid 13243 (vision.examples), pid 13243 (vision.examples)`
> 2. Could you please confirm that your device is not rooted.

```
2020-06-26 11:13:27.166 16401-16463/com.mapbox.vision.examples E/AndroidRuntime: FATAL EXCEPTION: VideoDecode
    Process: com.mapbox.vision.examples, PID: 16401
    java.lang.IllegalArgumentException
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:76)
        at com.mapbox.vision.examples.ExternalVideoSourceActivityKt.startFileVideoSource(ExternalVideoSourceActivityKt.kt:147)
        at com.mapbox.vision.examples.ExternalVideoSourceActivityKt.access$startFileVideoSource(ExternalVideoSourceActivityKt.kt:37)
        at com.mapbox.vision.examples.ExternalVideoSourceActivityKt$customVideoSource$1$attach$1.run(ExternalVideoSourceActivityKt.kt:54)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2020-06-26 11:13:27.227 16401-16401/com.mapbox.vision.examples I/vision.examples: type=1400 audit(0.0:2269): avc: denied { getattr } for path="/system/xbin/su" dev="dm-0" ino=38 scontext=u:r:untrusted_app:s0:c100,c256,c512,c768 tcontext=u:object_r:su_exec:s0 tclass=file permissive=1
2020-06-26 11:13:27.269 16401-16401/com.mapbox.vision.examples A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x24 in tid 16401 (vision.examples), pid 16401 (vision.examples)
```
And I would definitely say its rooted. How would that effect it?

**Comment by kiryldz** [comment]
You should see, that a bunch of launcher icons appear when you build examples.
Error you pasted above is related to `ExternalVideoSourceActivityKt` - you could play your custom video file from device external storage by providing path to this file (line 41 in `ExternalVideoSourceActivityKt.kt`)
```
private const val PATH_TO_VIDEO_FILE = "path_to_video_file"
```
