### ISSUE TITLE
Failed resolution of: Lcom/mapbox/vision/mobile/core/models/Country

### ISSUE THREAD

**Issue by frankSol** [mapbox/mapbox-vision-android#77]
Hello

I can't find vision.mobile.core.models.Coutry library

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.vision.mobile.core.models.Country" on path: DexPathList[[zip file "/data/app/hy.frank.ex.hyvisontest-JScYKGhpUduYYq7AnLwSRA==/base.apk"],nativeLibraryDirectories=[/data/app/hy.frank.ex.hyvisontest-JScYKGhpUduYYq7AnLwSRA==/lib/arm64, /data/app/hy.frank.ex.hyvisontest-JScYKGhpUduYYq7AnLwSRA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.mapbox.vision.VisionManager.<clinit>(VisionManager.kt:71) 
        at hy.frank.ex.hyvisontest.VisionApp.onCreate(VisionApp.java:16) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6217) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7045) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 

I downloaded and import vision aar file like this.

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation files('libs/mapbox-android-vision-0.3.0.aar')
    implementation files('libs/mapbox-android-vision-native-0.3.0.aar')
    implementation files('libs/mapbox-android-vision-ar-0.3.0.aar')
    implementation files('libs/mapbox-android-vision-ar-native-0.3.0.aar')
    implementation files('libs/mapbox-android-vision-safety-0.3.0.aar')
    implementation files('libs/mapbox-android-vision-safety-native-0.3.0.aar')

    implementation "com.mapbox.mapboxsdk:mapbox-android-sdk:6.6.1"
    implementation "com.mapbox.mapboxsdk:mapbox-android-navigation:0.2.0"
    implementation "com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.8.2"
    implementation "com.mapbox.mapboxsdk:mapbox-android-core:0.2.1"
}

But It can't find mabox.vision.mobile package.
So I ask that having mistake or not.

Thanks

**Comment by yunikkk** [comment]
Hello @frankSol , how do you retrieved vision dependencies?

**Comment by yunikkk** [comment]
Seems that proguard might be an issue, do you use it with your application?

**Comment by vladzima** [comment]
Closing this for now. Feel free to reopen if needed.
